[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/app/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/auth/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/seller/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
